swagger: '2.0'
info:
  title: Luna.Partner.Functions
  version: V1
host: localhost:7071
schemes:
  - http
paths:
  /api/partnerServices/hostservicetypes:
    get:
      tags:
        - Metadata
      summary: Get ML host service types
      operationId: getApiPartnerServicesHostservicetypes
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Partner.Public.Client.ServiceType'
      security:
        - x-functions-key: [ ]
  /api/partnerServices/computeservicetypes:
    get:
      tags:
        - Metadata
      summary: Get ML compute service types
      operationId: getApiPartnerServicesComputeservicetypes
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Partner.Public.Client.ServiceType'
      security:
        - x-functions-key: [ ]
  '/api/partnerServices/{serviceType}/mlcomponenttypes':
    get:
      tags:
        - Metadata
      summary: Get ML component types
      operationId: getApiPartnerServicesByServiceTypeMlcomponenttypes
      produces:
        - application/json
      parameters:
        - in: path
          name: serviceType
          description: The ML host service type
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Partner.Public.Client.ComponentType'
      security:
        - x-functions-key: [ ]
  '/api/partnerServices/{serviceName}/mlcomponents/{componentType}':
    get:
      tags:
        - Metadata
      summary: Get ML components by type
      operationId: getApiPartnerServicesByServiceNameMlcomponentsByComponentType
      produces:
        - application/json
      parameters:
        - in: path
          name: serviceName
          description: The partner service name
          required: true
          type: string
        - in: path
          name: componentType
          description: The ML component type
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Partner.Public.Client.BaseMLComponent'
      security:
        - x-functions-key: [ ]
  '/api/partnerServices/{name}':
    get:
      tags:
        - Partner service
      summary: Get a partner service
      operationId: getApiPartnerServicesByName
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the partner service
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Partner.Public.Client.BasePartnerServiceConfiguration'
      security:
        - x-functions-key: [ ]
    patch:
      tags:
        - Partner service
      summary: Update a partner service
      operationId: patchApiPartnerServicesByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the partner service
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Partner.Public.Client.BasePartnerServiceConfiguration'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Partner.Public.Client.BasePartnerServiceConfiguration'
      security:
        - x-functions-key: [ ]
    put:
      tags:
        - Partner service
      summary: Add a partner service
      operationId: putApiPartnerServicesByName
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: name
          description: Name of the partner service
          required: true
          type: string
        - in: body
          name: body
          description: Request contract
          required: true
          schema:
            $ref: '#/definitions/Luna.Partner.Public.Client.BasePartnerServiceConfiguration'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Luna.Partner.Public.Client.BasePartnerServiceConfiguration'
      security:
        - x-functions-key: [ ]
  /api/partnerServices:
    get:
      tags:
        - Partner service
      summary: List partner services by type
      operationId: getApiPartnerServices
      produces:
        - application/json
      parameters:
        - in: query
          name: type
          description: Partner service type
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Luna.Partner.Public.Client.BasePartnerServiceConfiguration'
      security:
        - x-functions-key: [ ]
definitions:
  Luna.Partner.Public.Client.ServiceType:
    required:
      - Id
      - DisplayName
    type: object
    properties:
      Id:
        type: string
      DisplayName:
        type: string
  Luna.Partner.Public.Client.ComponentType:
    required:
      - Id
      - DisplayName
    type: object
    properties:
      Id:
        type: string
      DisplayName:
        type: string
  Luna.Partner.Public.Client.BaseMLComponent:
    required:
      - Type
      - Id
      - Name
    type: object
    properties:
      Type:
        type: string
      Id:
        type: string
      Name:
        type: string
  Luna.Partner.Public.Client.BasePartnerServiceConfiguration:
    required:
      - DisplayName
      - Description
      - Type
    type: object
    properties:
      DisplayName:
        type: string
      Description:
        type: string
      Type:
        type: string
      Tags:
        type: string
    example:
      DisplayName: My Azure ML workspace
      Description: Azure ML workspace
      Type: AzureML
      Tags: ''
securityDefinitions:
  x-functions-key:
    type: apiKey
    name: x-functions-key
    in: header
    description: Azure function key